### ISSUE TITLE
Dev nodes hang after deploying `1d360c6`

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#1371]
After deploying [this](https://github.com/ipni/storetheindex/commit/54c18b6556ddef3df05a80529bc1ebc864363796) commit, `cali` and `ber` seem to hang while instantiating the ingester. Logs:

```
Found storetheindex repo at /config
{"level":"info","ts":"2023-03-07T19:26:46.674Z","logger":"indexer","caller":"command/daemon.go:521","msg":"Valuestore initializing/opening","type":"pebble","path":"/data/valuestore"}
{"level":"info","ts":"2023-03-07T19:26:46.924Z","logger":"indexer","caller":"command/daemon.go:107","msg":"Valuestore initialized"}
{"level":"info","ts":"2023-03-07T19:26:46.966Z","logger":"indexer","caller":"command/daemon.go:147","msg":"Result cache disabled"}
{"level":"info","ts":"2023-03-07T19:26:46.991Z","logger":"indexer/registry","caller":"registry/registry.go:282","msg":"Loaded providers into registry","count":212}
{"level":"info","ts":"2023-03-07T19:26:46.996Z","logger":"indexer/registry","caller":"registry/registry.go:289","msg":"Loaded assignments into registry","count":262}
{"level":"info","ts":"2023-03-07T19:26:47.002Z","logger":"indexer/freezer","caller":"freeze/freezer.go:231","msg":"Disk usage OK","usage":"26.87%","freezeAt":"90%"}
{"level":"info","ts":"2023-03-07T19:26:47.003Z","logger":"indexer","caller":"command/daemon.go:225","msg":"libp2p resource manager disabled"}
{"level":"info","ts":"2023-03-07T19:26:47.011Z","logger":"indexer/ingest","caller":"ingest/ingest.go:1222","msg":"rate limiting disabled"}
{"level":"info","ts":"2023-03-07T20:04:39.758Z","logger":"indexer/freezer","caller":"freeze/freezer.go:231","msg":"Disk usage OK","usage":"26.87%","freezeAt":"90%"}
```

Based on the logs above the code must be hanging while instantiating the ingester, because the logs show the info level message about rate limiting being disabled but not the next expected log about [libp2p servers initialising](https://github.com/ipni/storetheindex/blob/d0f5658f70d035d9e70bc92af1dd2d4c98e3aa0a/command/daemon.go#L275).

**Comment by masih** [comment]
Extra logs show that node seems to be hanging while waiting for data transfer manager to become ready:

```
Found storetheindex repo at /config
{"level":"info","ts":"2023-03-07T20:58:05.192Z","logger":"indexer","caller":"command/daemon.go:521","msg":"Valuestore initializing/opening","type":"pebble","path":"/data/valuestore"}
{"level":"info","ts":"2023-03-07T20:58:05.455Z","logger":"indexer","caller":"command/daemon.go:107","msg":"Valuestore initialized"}
{"level":"info","ts":"2023-03-07T20:58:05.493Z","logger":"indexer","caller":"command/daemon.go:147","msg":"Result cache disabled"}
{"level":"info","ts":"2023-03-07T20:58:05.517Z","logger":"indexer/registry","caller":"registry/registry.go:282","msg":"Loaded providers into registry","count":212}
{"level":"info","ts":"2023-03-07T20:58:05.522Z","logger":"indexer/registry","caller":"registry/registry.go:289","msg":"Loaded assignments into registry","count":262}
{"level":"info","ts":"2023-03-07T20:58:05.528Z","logger":"indexer/freezer","caller":"freeze/freezer.go:231","msg":"Disk usage OK","usage":"26.87%","freezeAt":"90%"}
{"level":"info","ts":"2023-03-07T20:58:05.528Z","logger":"indexer","caller":"command/daemon.go:225","msg":"libp2p resource manager disabled"}
{"level":"info","ts":"2023-03-07T20:58:05.536Z","logger":"indexer/ingest","caller":"ingest/ingest.go:1222","msg":"rate limiting disabled"}
{"level":"info","ts":"2023-03-07T20:58:05.537Z","logger":"dagsync/dtsync","caller":"dtsync/util.go:115","msg":"Started data transfer manager successfully."}
{"level":"info","ts":"2023-03-07T20:58:05.537Z","logger":"dagsync/dtsync","caller":"dtsync/util.go:118","msg":"Awaiting data transfer manager to become ready..."}
```

**Comment by masih** [comment]
`ber` has restarted 27 times since yesterday with the following error:
```
│ gCVu1Rt21NecM6Ma-1677173821478799127'; already tracking state in new db for '/12D3KooWSQpUgBZwbNuMN3ctZjMesnoH9UDhwEXroxParXQCgurN-12D3KooWSxsHih5wddi7W1HbBjkxXA3goJgugCVu1Rt21NecM6Ma-16771738214 │

```

**Comment by gammazero** [comment]
This looks like some DT FSM bug that has been leaving garbage state data behind for as long as we have been running the indexer (probably resulting from terminated sessions over time).  Now when we try to put a new version of DT in place there is too much accumulated garbage data to ever have a chance of finishing migration.

[This](https://github.com/filecoin-project/go-ds-versioning/blob/master/internal/migrate/migrate.go#L46-L90) is the endless (or at least super long) loop.  The loop continues all the way to the end and appends to keys, which keeps growing with keys that look like:
```
12D3KooWBHY2dGH8ngC6LjCiMC7JuRQf3DEb3Nk8neuntAGirb89-12D3KooW9tJKf3aKkpCp8DGjNg65PHBRnLWENEDpFEBEU5s7tEDC-1662230393911313922 /12D3KooWBHY2dGH8ngC6LjCiMC7JuRQf3DEb3Nk8neuntAGirb89-12D3KooW9tJKf3aKkpCp8DGjNg65PHBRnLWENEDpFEBEU5s7tEDC-1662230393911313924 /12D3KooWBHY2dGH8ngC6LjCiMC7JuRQf3DEb3Nk8neuntAGirb89-12D3KooW9tJKf3aKkpCp8DGjNg65PHBRnLWENEDpFEBEU5s7tEDC-1662230393911327153 /12D3KooWBHY2dGH8ngC6LjCiMC7JuRQf3DEb3Nk8neuntAGirb89-12D3KooW9tJKf3aKkpCp8DGjNg65PHBRnLWENEDpFEBEU5s7tEDC-1662230393911388295
```

Here is a stackdump from inside the loop.
```
goroutine 80 [running]:
github.com/filecoin-project/go-data-transfer/v2/channels/internal/migrations.MigrateChannelState2To3(0x1400243a900)
        /Users/ajg/protocollabs/filecoin/go-data-transfer/channels/internal/migrations/migrations.go:73 +0x338
reflect.Value.call({0x10632ebc0?, 0x1065f46d0?, 0x14000cde324?}, {0x105d20693, 0x4}, {0x14000595800, 0x1, 0x105b261e8?})
        /usr/local/go/src/reflect/value.go:586 +0x838
reflect.Value.Call({0x10632ebc0?, 0x1065f46d0?, 0x1063aa4c0?}, {0x14000595800?, 0x1065982e0?, 0x14002438400?})
        /usr/local/go/src/reflect/value.go:370 +0x90
github.com/filecoin-project/go-ds-versioning/internal/migrate.execute({0x106614290, 0x14000b525f0}, {0x10661a768?, 0x1400029e0e0?}, {0x0?, 0x0?}, {0x106620520, 0x140001ac780}, {0x10662f5a0, 0x1063aa4c0}, ...)
        /Users/ajg/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.2/internal/migrate/migrate.go:64 +0x2c4
github.com/filecoin-project/go-ds-versioning/internal/migrate.Execute({0x106614290, 0x14000b525f0}, {{0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...)
        /Users/ajg/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.2/internal/migrate/migrate.go:35 +0x1cc
github.com/filecoin-project/go-ds-versioning/pkg/builder.(*dsMigration).Up(0x140001ac780?, {0x106614290?, 0x14000b525f0?}, {0x106620520?, 0x140001ac340?}, {0x106620520?, 0x140001ac780?})
        /Users/ajg/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.2/pkg/builder/builder.go:95 +0xec
github.com/filecoin-project/go-ds-versioning/pkg/versioned.versionMigrate({0x106614290, 0x14000b525f0}, 0x14000595c90, {0x1066205e0?, 0x140001ac820}, {0x1061c33a0?, 0x0?}, {0x1061c33e0, 0x1})
        /Users/ajg/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.2/pkg/versioned/versioned.go:20 +0x1f0
github.com/filecoin-project/go-ds-versioning/pkg/versioned.versionedMigration.Up(...)
        /Users/ajg/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.2/pkg/versioned/versioned.go:38
github.com/filecoin-project/go-ds-versioning/internal/migrate.runMigrations({0x106614290, 0x14000b525f0}, {0x1066205e0, 0x140001ac820}, {0x1400004eb80, 0x2, 0x2}, {0x10718bef0, 0x1}, {0x1061c33e0, ...})
        /Users/ajg/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.2/internal/migrate/migrate.go:140 +0x1f4
github.com/filecoin-project/go-ds-versioning/internal/migrate.To({0x106614290, 0x14000b525f0}, {0x1066205e0, 0x140001ac820?}, {0x1400004eb80?, 0x2, 0x2}, {0x1061c33e0, 0x1})
        /Users/ajg/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.2/internal/migrate/migrate.go:128 +0x208
github.com/filecoin-project/go-ds-versioning/internal/runner.(*Runner).Migrate.func1.1()
        /Users/ajg/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.2/internal/runner/runner.go:45 +0x50
sync.(*Once).doSlow(0x1056abb40?, 0x14000c04c80?)
        /usr/local/go/src/sync/once.go:74 +0x100
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:65
github.com/filecoin-project/go-ds-versioning/internal/runner.(*Runner).Migrate.func1()
        /Users/ajg/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.2/internal/runner/runner.go:44 +0x58
created by github.com/filecoin-project/go-ds-versioning/internal/runner.(*Runner).Migrate
        /Users/ajg/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.2/internal/runner/runner.go:43 +0x9c
```
In [github.com/filecoin-project/go-ds-versioning/pkg/versioned/versioned.go:20](http://github.com/filecoin-project/go-ds-versioning/pkg/versioned/versioned.go:20), the from-version is 2 and the to-version is 3.

The `MigrateChannelState2To3` function, [here](https://github.com/filecoin-project/go-data-transfer/blob/master/channels/internal/migrations/migrations.go#L73), is called in an endless loop.

**Comment by masih** [comment]
@gammazero I think from IPNI perspective this issue can be closed. Right?

**Comment by gammazero** [comment]
This is a DT FSM migration issue, so closing.
