### ISSUE TITLE
Back up `ber` datastore and provide a copy to Tornado team for debugging

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#1379]
Back up the `ber` node datastore in `dev` and send to @hannahhoward  for debugging the FSM migration issue.

The datastore is of type leveldb and uses no namespace or key prefix for storing data transfer FSMs.

**Comment by gammazero** [comment]
This looks like some DT FSM bug that has been leaving garbage state data behind for as long as we have been running the indexer (probably resulting from terminated sessions over time).  Now when we try to put a new version of DT in place there is too much accumulated garbage data to ever have a chance of finishing migration.

[This](https://github.com/filecoin-project/go-ds-versioning/blob/master/internal/migrate/migrate.go#L46-L90) is the endless (or at least super long) loop.  The loop continues all the way to the end and appends to keys, which keeps growing with keys that look like:
```
12D3KooWBHY2dGH8ngC6LjCiMC7JuRQf3DEb3Nk8neuntAGirb89-12D3KooW9tJKf3aKkpCp8DGjNg65PHBRnLWENEDpFEBEU5s7tEDC-1662230393911313922 /12D3KooWBHY2dGH8ngC6LjCiMC7JuRQf3DEb3Nk8neuntAGirb89-12D3KooW9tJKf3aKkpCp8DGjNg65PHBRnLWENEDpFEBEU5s7tEDC-1662230393911313924 /12D3KooWBHY2dGH8ngC6LjCiMC7JuRQf3DEb3Nk8neuntAGirb89-12D3KooW9tJKf3aKkpCp8DGjNg65PHBRnLWENEDpFEBEU5s7tEDC-1662230393911327153 /12D3KooWBHY2dGH8ngC6LjCiMC7JuRQf3DEb3Nk8neuntAGirb89-12D3KooW9tJKf3aKkpCp8DGjNg65PHBRnLWENEDpFEBEU5s7tEDC-1662230393911388295
```

Here is a stackdump from inside the loop.
```
goroutine 80 [running]:
github.com/filecoin-project/go-data-transfer/v2/channels/internal/migrations.MigrateChannelState2To3(0x1400243a900)
        /Users/ajg/protocollabs/filecoin/go-data-transfer/channels/internal/migrations/migrations.go:73 +0x338
reflect.Value.call({0x10632ebc0?, 0x1065f46d0?, 0x14000cde324?}, {0x105d20693, 0x4}, {0x14000595800, 0x1, 0x105b261e8?})
        /usr/local/go/src/reflect/value.go:586 +0x838
reflect.Value.Call({0x10632ebc0?, 0x1065f46d0?, 0x1063aa4c0?}, {0x14000595800?, 0x1065982e0?, 0x14002438400?})
        /usr/local/go/src/reflect/value.go:370 +0x90
github.com/filecoin-project/go-ds-versioning/internal/migrate.execute({0x106614290, 0x14000b525f0}, {0x10661a768?, 0x1400029e0e0?}, {0x0?, 0x0?}, {0x106620520, 0x140001ac780}, {0x10662f5a0, 0x1063aa4c0}, ...)
        /Users/ajg/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.2/internal/migrate/migrate.go:64 +0x2c4
github.com/filecoin-project/go-ds-versioning/internal/migrate.Execute({0x106614290, 0x14000b525f0}, {{0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...)
        /Users/ajg/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.2/internal/migrate/migrate.go:35 +0x1cc
github.com/filecoin-project/go-ds-versioning/pkg/builder.(*dsMigration).Up(0x140001ac780?, {0x106614290?, 0x14000b525f0?}, {0x106620520?, 0x140001ac340?}, {0x106620520?, 0x140001ac780?})
        /Users/ajg/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.2/pkg/builder/builder.go:95 +0xec
github.com/filecoin-project/go-ds-versioning/pkg/versioned.versionMigrate({0x106614290, 0x14000b525f0}, 0x14000595c90, {0x1066205e0?, 0x140001ac820}, {0x1061c33a0?, 0x0?}, {0x1061c33e0, 0x1})
        /Users/ajg/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.2/pkg/versioned/versioned.go:20 +0x1f0
github.com/filecoin-project/go-ds-versioning/pkg/versioned.versionedMigration.Up(...)
        /Users/ajg/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.2/pkg/versioned/versioned.go:38
github.com/filecoin-project/go-ds-versioning/internal/migrate.runMigrations({0x106614290, 0x14000b525f0}, {0x1066205e0, 0x140001ac820}, {0x1400004eb80, 0x2, 0x2}, {0x10718bef0, 0x1}, {0x1061c33e0, ...})
        /Users/ajg/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.2/internal/migrate/migrate.go:140 +0x1f4
github.com/filecoin-project/go-ds-versioning/internal/migrate.To({0x106614290, 0x14000b525f0}, {0x1066205e0, 0x140001ac820?}, {0x1400004eb80?, 0x2, 0x2}, {0x1061c33e0, 0x1})
        /Users/ajg/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.2/internal/migrate/migrate.go:128 +0x208
github.com/filecoin-project/go-ds-versioning/internal/runner.(*Runner).Migrate.func1.1()
        /Users/ajg/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.2/internal/runner/runner.go:45 +0x50
sync.(*Once).doSlow(0x1056abb40?, 0x14000c04c80?)
        /usr/local/go/src/sync/once.go:74 +0x100
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:65
github.com/filecoin-project/go-ds-versioning/internal/runner.(*Runner).Migrate.func1()
        /Users/ajg/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.2/internal/runner/runner.go:44 +0x58
created by github.com/filecoin-project/go-ds-versioning/internal/runner.(*Runner).Migrate
        /Users/ajg/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.2/internal/runner/runner.go:43 +0x9c
```
In [github.com/filecoin-project/go-ds-versioning/pkg/versioned/versioned.go:20](http://github.com/filecoin-project/go-ds-versioning/pkg/versioned/versioned.go:20), the from-version is 2 and the to-version is 3.

The `MigrateChannelState2To3` function, [here](https://github.com/filecoin-project/go-data-transfer/blob/master/channels/internal/migrations/migrations.go#L73), is called in an endless loop.

**Comment by gammazero** [comment]
Ber data store is backed up into a tar file. This has been copied to S3 and a URL delivered to @hannahhoward
