### ISSUE TITLE
Panic when receiving same pubsub message

### ISSUE THREAD

**Issue by gammazero** [ipni/storetheindex#1512]
To reproduce, use index-provider, import car file, and then use `provider announce` multiple times in a short amount of time.  This will cause the indexer to panic with the following:
```
panic: putting the same entry twice not supported                    
                                                                                                                                                 
goroutine 181 [running]:                                                                                                                         
github.com/libp2p/go-libp2p-pubsub/timecache.FirstSeenCache.Add({0x14001fdc9f0?, 0x14001fdca20?, 0x14001ff8000?, 0x14001f98048?}, {0x1400011e160, 0x20})
        /Users/ajg/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.9.0/timecache/first_seen_cache.go:32 +0x264
github.com/libp2p/go-libp2p-pubsub.(*PubSub).markSeen(0x14001ffc000, {0x1400011e160, 0x20})
        /Users/ajg/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.9.0/pubsub.go:1002 +0x124
github.com/libp2p/go-libp2p-pubsub.(*validation).validate(0x14001fac140, {0x0, 0x0, 0x0?}, {0x14001dc6210, 0x26}, 0x14001fac000, 0x0)
        /Users/ajg/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.9.0/validation.go:288 +0xe8
github.com/libp2p/go-libp2p-pubsub.(*validation).validateWorker(0x14001fac140)
        /Users/ajg/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.9.0/validation.go:266 +0x4c
created by github.com/libp2p/go-libp2p-pubsub.(*validation).Start
        /Users/ajg/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.9.0/validation.go:133 +0x6c
```

**Comment by gammazero** [comment]
This issue is difficult to reproduce. Steps to most reliably reproduce issue:
1. Start new indexer
2. Start new index-provider (peered with indexer)
3. Import car file into index-provider, and see that indexer ingests it.
4. Stop index-provider and delete index-provider data store
5. Wait 2 minutes and start index provider
6. Import same car file as before
7. See that indexer panics
